name: Verify API Reference Sync

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  verify-api-reference:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run verification
        run: |
          python scripts/verify_api_reference.py
