name: Python tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        env:
          PYTHONWARNINGS: "ignore"
        run: |
          pytest --maxfail=1 --disable-warnings --cov=src --cov-report=term-missing --cov-fail-under=35

      - name: Upload coverage XML
        if: always()
        run: |
          pytest --cov=src --cov-report=xml -q
        continue-on-error: true
      - name: Store coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
